name: ssdm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy<2.0
  - pandas
  - librosa
  - matplotlib
  - holoviews
  - cycler
  - xarray
  - scikit-learn
  - scipy
  - python-igraph
  - tqdm
  - pytorch
  - wandb
  - pytest
  - ipykernel
  - mir_eval
  - timm
  - lightning
  - cython
  - dataset
  - pip
  - pip:
    - openl3
    - crema
    - madmom
    - jams
    - tensorflow==2.15.0
    - keras==2.15.0
    - tensorflow-hub==0.15.0
    - tensorflow-metal